project:
  type: website

website:
  title: "George Gu's AI blogs"
  description: "George Gu's blogs about large language models, multi modal models and alignments."
  site-url: https://georgegu.github.io/georgegu-ai-blogs
  navbar:
    left:
      - text: "{{< fa pen >}} Notes"
        file: notes.qmd
      - text: "{{< fa address-card >}} About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/GeorgeGu
      - icon: linkedin
        href: https://linkedin.com/in/georgegu06/
    pinned: false
  favicon: images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "{{< fa regular copyright >}} Copyright 2024, George Gu" 

  sidebar:
    - id: articles
      title: "Articles"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "🗣️ **Large language models**"
          contents:
            - text: "1. Fine-tune Llama 2 in Colab"
              href: posts/Fine_Tune_Your_Own_Llama_2_Model_in_a_Colab_Notebook.html
        - text: "---"

    - id: notes
      title: "Notes"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "🗣️ **Large language models**"
          contents: "notes/Large Language Models/*"
        - text: "---"
format:
  html:
    page-layout: article
    theme: [minty, styles.scss]
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    css: styles.css
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: true

comments:
  utterances:
    repo: https://github.com/georgegu/georgegu-ai-blogs
